### ISSUE TITLE
Does this work with Koa 2?

### ISSUE THREAD

**Issue by corysimmons** [technicallyjosh/koa-jwt-roles#1]
If not, could it be? :D

**Comment by dotjoshrc** [comment]
It doesn't at the moment. I can update it no problem. v1 will work with koa 2.

**Comment by dotjoshrc** [comment]
Just updated v1 for Koa 2. Keep in mind this is not transpiled for async/await so node 7.6+ is needed. The call of the library is exactly the same. Happy coding :)

**Comment by corysimmons** [comment]
@technicallyjosh You da best!

![image](https://user-images.githubusercontent.com/224636/29555268-18a03c50-86f0-11e7-8dad-bebf0add6a7d.png)
