### ISSUE TITLE
Where does the role come from?

### ISSUE THREAD

**Issue by corysimmons** [technicallyjosh/koa-jwt-roles#2]
Is it part of the JWT payload? If so, what's they key? `role`?

Sorry if this is easy, newb to everything. 😬

**Comment by corysimmons** [comment]
Never mind, I think I get how it works.

**Comment by dotjoshrc** [comment]
Yeah it's the roles property in the JWT token. I know that there is a way to set that property to whatever you want in jsonwebtoken but I haven't thought about the ability to set that in this package to adhere to the change.

**Comment by corysimmons** [comment]
When you `jwt.verify` you pass the token as first arg and a callback. In that callback you get your decoded payload and can set `ctx.state.user.roles` to it.

I ended up just doing something _really_ simple instead:

```js
router.get(`/protected`, ctx => {
  if (!ctx.state.jwt.role.match(/admin|mod/)) ctx.throw(403)
  ...
})
```

I'll probably wrap that little thing up into some middleware so it's even more terse:

```js
router.get(`/protected`, ctx => {
  roles(['admin', 'mod']) // or something
  ...
})
```
